# Generated by Django 5.1.7 on 2025-04-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
